// <auto-generated/>
namespace Combinator.Tests;

using Combinator;
using NUnit.Framework;

public class ConcreteSourceTests
{
  private record TestSource(int Amount, bool IsActive);

  [TestCase(5, true, true, TestName = "Amount_Is_Between_4_And_6_And_Is_Active_Is_T_Returns_T")]
  [TestCase(4, true, false, TestName = "Amount_Is_4_And_Is_Active_Is_T_Returns_F")]
  [TestCase(6, true, false, TestName = "Amount_Is_6_And_Is_Active_Is_T_Returns_F")]
  [TestCase(5, false, false, TestName = "Amount_Is_5_And_Is_Active_Is_F_Returns_F")]
  public void ConcreteSourceWhereAndReturnsExpectedResult(
    int amount,
    bool isActive,
    bool expected
  )
  {

    var result = Combinator<TestSource>
      .Where(source => source.Amount > 4)
      .And(source => source.Amount < 6)
      .And(source => source.IsActive is true)
      .Using(new TestSource(amount, isActive));

    Assert.That(result, Is.EqualTo(expected));
  }
}
